### PR TITLE
Remove unneeded strip

### PR DESCRIPTION
**Pull request by FWeinb**
I removed the unneeded strip regex and function. So there is one regex less that can break. Tests are all working fine.

### CODE REVIEW

**Comment by toddmotto** [comment]
Thanks man, would you be able to do a version bump in `package.json` then run `gulp`, this will rebuild the `/dist/` files? Cheers!

**Comment by FWeinb** [comment]
Did so but we should fix this:

``` shell
/Users/FWeinb/GitHub/interpolate/src/interpolate.js
  line 41  col 34  The Function constructor is a form of eval.
  line 42  col 39  Strings must use singlequote.
  line 42  col 59  Strings must use singlequote.
  line 42  col 78  Strings must use singlequote.
  line 42  col 90  Strings must use singlequote.
  line 42  col 80  'code' is not defined.

✖ 6 problems
```

Another PR?

**Comment by toddmotto** [comment]
Definitely, although `Function` can stay... Can we turn off the jsHint for that?

I think it'd be better to `throw new Error()` here inside the `catch` too, thoughts? Indentation lost here too.

``` js
catch(err) { console.error("'" + err.message + "'", " in \n\nCode:\n", code, "\n"); }
```

**Comment by FWeinb** [comment]
Will you merge this? Than I can refactor it and fix all the lint errors. What about the `code` variable. It isn't defined currently?

**Comment by toddmotto** [comment]
Boom!

**Pull request merged**
