### PR TITLE
Interpolate deep properties

### PR DESCRIPTION
**Pull request by WickyNilliams**
Previously you could only go one level deep for variable replacement, now you can go arbitrarily deep. So this kind of template is now supported:

``` js
var template = '<span>{{ favourite.language }}</span>';
var data     = { favourite : { language : 'JavaScript' };
var render   = interpolate(template);

console.log(render(data)); // <span>JavaScript</span>
```

### CODE REVIEW

**Comment by toddmotto** [comment]
Awesomely suave. Thanks man, wondering if you think the RegExp should live on the `Interpolate` Object tho?

**Comment by WickyNilliams** [comment]
Yeah I didn't know what was best to do with that. My thinking was it's a static property so I put it there. 

Could make it private if you like, you're best to decide there :) Alternatively could accept an option to interpolate and allow people to optionally define the delimiters as an option, some people like the erb style `<%= propName %>`.  Your call!

**Comment by toddmotto** [comment]
Might stick it in as private, only to save the creation each time, nothing huge or urgent.

Custom interpolation would be cool, however it'd require another method, and this function I grabbed from Google:

``` js
var escapeForRegexp = function (str) {
  return str.replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g, '\\$1').replace(/\x08/g, '\\x08');
};
```

Escapes custom interpolation symbols (well, special chars) for you as RegExp, love it. There will be a few other things that need overriding and persisting as well - I'm not sure the aim of this module is big enough to warrant it though.

**Comment by WickyNilliams** [comment]
It won't be created every time as it is. Not sure if I'm misunderstanding you there?

Anyway, I agree, may be unnecessary complexity. Go forth and make it private!

**Comment by toddmotto** [comment]
Currently it calls `new Interpolate()`, creating the new Object, so surely the property needs "creating" for each instance, rather than it just being static in the private scope?

**Comment by WickyNilliams** [comment]
It's a property on the Interpolate function, not assigned in the constructor itself so should be a single, consistent object (which is why we refer delimiters to it as Interpolate.reDelimeters instead of this.reDelimeters)? I may be entirely wrong, test it and let me know! 

Though I've just noticed I spelt delimiters incorrectly in the code haha

**Comment by toddmotto** [comment]
Oh yeah, shoot. Now I don't know either - haha! Perhaps it doesn't then, I
think you're right actually. Oh, let me update that.

On 8 July 2014 20:26, Nick Williams notifications@github.com wrote:

> It's a property on the Interpolate function, not assigned in the
> constructor itself so should be a single, consistent object (which is why
> we refer delimiters to it as Interpolate.reDelimeters instead of
> this.reDelimeters)? I may be entirely wrong, test it and let me know!
> 
> Though I've just noticed I spelt delimiters incorrectly in the code haha
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/toddmotto/interpolate/pull/3#issuecomment-48388156.

## 

Todd Motto | +44 7557 149 519
Lead front-end engineer
toddmotto.com | @toddmotto

**Pull request merged**
