### PR TITLE
interpolate deep properties

### PR DESCRIPTION
**Pull request by WickyNilliams**
Previously you could only go one level deep for variable replacement, now you can go arbitrarily deep. So this kind of template is now supported:

``` js
var template = '<span>{{ favourite.language }}</span>';
var data     = { favourite : { language : 'JavaScript' };
var render   = interpolate(template);

console.log(render(data)); // <span>JavaScript</span>
```

### CODE REVIEW

**Comment by toddmotto** [comment]
Ha - was talking about this exact thing this morning. Thanks man, great work.

**Comment by toddmotto** [comment]
Actually, I've just reverted it - I was trying to avoid ES5 methods (such as `reduce`) to leave it open for lesser loved browsers, would you be good swapping it out mate?

**Comment by WickyNilliams** [comment]
Had some time spare time at lunch so thought I would be a good open source citizen :)

Argh, sorry mate. I'm back working now, will swap it out later if that's cool by you.

**Comment by toddmotto** [comment]
Yes definitely, no rush! Will give it a version bump after you add the feat too. My bad for pulling too quick :dancer:

**Comment by WickyNilliams** [comment]
I think I'm going to have to create an entirely new PR...

I've pushed a new commit to the old branch and when i click to make a PR it says there's only one commit pending (my fix for reduce, doesn't recognise the old commit).

So to avoid any pain, I'll just start afresh.

**Pull request merged**
